name: Send Test Message to Hookdeck

on:
  schedule:
    - cron: '0 0 * * *'


jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Send test message to Hookdeck
      run: |
        curl -X POST \
        -H "Content-Type: application/json" \
        -d '{
          "username": "Report Bot",
          "content": "Make sure to **REPORT** any Bug from the game!"
        }' \
        https://hkdk.events/opg988b9wwdqda
